### ISSUE TITLE
No GUI in aarch64 (e.g. Raspberry Pi) build

### ISSUE THREAD

**Issue by gregnukem** [AIPowerGrid/AI-Power-Grid-Core#10]
The released version of the aarch64 application v1.1.2 (AI-Power-Grid-Core-1.1.2-aarch64-linux-gnu.tar.gz) contains no graphics interface executable (aipg-qt). Probably an error during compilation?

**Comment by Seal-Clubber** [comment]
Here you can find the updated binaries for [aarch64](https://github.com/AIPowerGrid/AI-Power-Grid-Core/releases/download/v1.1.3/AI-Power-Grid-Core-1.1.3-aarch64-linux-gnu.tar.gz)
