### ISSUE TITLE
No application exe in win x64 core zip

### ISSUE THREAD

**Issue by freegold** [AIPowerGrid/AI-Power-Grid-Core#11]
### Describe the issue
Downloaded win x64 from aipowergrid website (and then github), zip contains only bin, include, lib & share folders
### Can you reliably reproduce the issue?
Sure
#### If so, please list the steps to reproduce below:
1.Download x64 win core
2.Unzip
3.

### Expected behaviour
Tell us what should happen
I hoped to find an application exe to launch the core in windows

### Actual behaviour
Tell us what happens instead
Nothing just an unzipped folder

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of Ravencoin are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by halfaipg** [comment]
/bin/aipg-qt.exe

**Comment by freegold** [comment]
thanks :)
