### ISSUE TITLE
Cross compilation fail!

### ISSUE THREAD

**Issue by DebianUser007** [AIPowerGrid/AI-Power-Grid-Core#15]
### Describe the issue
Cross-compilation on Debian Bookkworm lxqt latest version failed with errors.
sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl nsis
selected the 'posix' variant for both
sudo update-alternatives --config x86_64-w64-mingw32-g++
sudo update-alternatives --config x86_64-w64-mingw32-gcc
sudo apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
Then build using:
PATH=$(echo "$PATH" | sed -e 's/:/mnt.*//g') # strip out problematic Windows %PATH% imported var
cd depends
make HOST=x86_64-w64-mingw32 -j5
cd ..
./autogen.sh
contrib/install_db4.sh ../
export BDB_PREFIX=/root/db4
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --prefix=/ --enable-cxx --disable-shared --disable-tests --disable-gui-tests --with-pic
make -j5
and I got errors in notificator.cpp

### Can you reliably reproduce the issue?
sure

### Expected behaviour
I wanted to build an application exe for windows x64 . In the future for x32

### Actual behaviour
failed with errors in notificator.cpp

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.
![btcf0](https://github.com/AIPowerGrid/AI-Power-Grid-Core/assets/141000384/a24789e1-c59e-4022-a238-a910aedbd81b)

### What version of AIPG are you using?
latest version

### Machine specs:
- OS: Debian LXQT
- CPU: Ryzen 2200G
- RAM: 32 
- Disk size: 2TB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
In the screenshot above

**Comment by Seal-Clubber** [comment]
Cross-comp is made for ubuntu, for Debian use conventional build methods.

**Comment by DebianUser007** [comment]
> Cross-comp is made for ubuntu, for Debian use conventional build methods.
Ubuntu depends on Debian, Ubuntu is actually Debian based or Am I missing something here?. I of course will give it a shot to build on Ubuntu but I'm sure that isn't the real issue. Also for Linux, I built on Debian and it was successful and the QT wallet is working correctly, but when I tried to build for Windows, the problem started with several errors in notificator.cpp, which is located in the qt folder.

**Comment by Seal-Clubber** [comment]
The static builds are made with ubu18, for example ubu20 requires a different setup for builds with deps, that could also be the case with your Debian version.

**Comment by DebianUser007** [comment]
> The static builds are made with ubu18, for example ubu20 requires a different setup for builds with deps, that could also be the case with your Debian version.
I really appreciate your answer, I'll try what you recommend, thank you so much for the quick response. Actually I am using Debian bookworm which is the latest version

**Comment by DebianUser007** [comment]
> The static builds are made with ubu18, for example ubu20 requires a different setup for builds with deps, that could also be the case with your Debian version.
Just wanted to say that I finally built it successfully and got qt.exe.
