### ISSUE TITLE
Wallet earnings were transferred without reason under Windows

### ISSUE THREAD

**Issue by chenlerry** [AIPowerGrid/AI-Power-Grid-Core#25]
<img width="1329" alt="image" src="https://github.com/user-attachments/assets/35a92c3a-54fc-4b7c-8b2d-a42327f44825">

What is the problem with the transfer of profits for Windows client user version 1.1.3 when the node is continuously closed and a password is set?

**Comment by halfaipg** [comment]
The only way this could happen is if your seed phrase or private keys were exposed
